In [1]:
import pandas as pd
import numpy as np
data=pd.read_csv(r"F:\I-Neuron\22-OCT-END-TO-END-PROJECT\notebooks\data\gemstone.csv")

In [2]:
data.drop(columns="id")

        carat        cut color clarity  depth  table     x     y     z  price
0        1.52    Premium     F     VS2   62.2   58.0  7.27  7.33  4.55  13619
1        2.03  Very Good     J     SI2   62.0   58.0  8.06  8.12  5.05  13387
2        0.70      Ideal     G     VS1   61.2   57.0  5.69  5.73  3.50   2772
3        0.32      Ideal     G     VS1   61.6   56.0  4.38  4.41  2.71    666
4        1.70    Premium     G     VS2   62.6   59.0  7.65  7.61  4.77  14453
...       ...        ...   ...     ...    ...    ...   ...   ...   ...    ...
193568   0.31      Ideal     D    VVS2   61.1   56.0  4.35  4.39  2.67   1130
193569   0.70    Premium     G    VVS2   60.3   58.0  5.75  5.77  3.47   2874
193570   0.73  Very Good     F     SI1   63.1   57.0  5.72  5.75  3.62   3036
193571   0.34  Very Good     D     SI1   62.9   55.0  4.45  4.49  2.81    681
193572   0.71       Good     E     SI2   60.8   64.0  5.73  5.71  3.48   2258

[193573 rows x 10 columns]

In [3]:
# dependent ana independent column
x = data.drop(columns="price")
y=data[["price"]]

In [4]:
# segregate categorical and numerical column
cat_column=x.columns[x.dtypes=="object"]
num_column=x.columns[x.dtypes!="object"]
x_numercal_data=x[num_column]
x_categorical_data=x[cat_column]
x_categorical_data

              cut color clarity
0         Premium     F     VS2
1       Very Good     J     SI2
2           Ideal     G     VS1
3           Ideal     G     VS1
4         Premium     G     VS2
...           ...   ...     ...
193568      Ideal     D    VVS2
193569    Premium     G    VVS2
193570  Very Good     F     SI1
193571  Very Good     D     SI1
193572       Good     E     SI2

[193573 rows x 3 columns]

In [5]:
x_cat_data=x.select_dtypes(include="object")
x_num_data=x.select_dtypes(exclude="object")

In [6]:
x_cat_data_col=x_cat_data.columns
x_num_data_col=x_num_data.columns

x_num_data_col

Index(['id', 'carat', 'depth', 'table', 'x', 'y', 'z'], dtype='object')

In [7]:
cut_categorical = ["Fair","Good","Very Good","Premium","Ideal"]
clarity_categorical = ["I1","SI2","SI1","VS2","VS1","VVS2","VVS1","IF"]
color_categorical = ["D","E","F","G","H","I","J"]

In [8]:
from sklearn.impute import SimpleImputer  #handling missing value
from sklearn.preprocessing import OrdinalEncoder  #ordinal encoder
from sklearn.preprocessing import StandardScaler # handling feature scaling
#preprocessing
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [9]:
numeric_pipeline=Pipeline(


    steps=[

        ("imputer",SimpleImputer()),
        ("scaler",StandardScaler())





    ]
)

In [10]:
categorical_pipeline=Pipeline(




            steps=[

        ("imputer",SimpleImputer(strategy='most_frequent')),
        ("ordinalencoder",OrdinalEncoder(categories=[cut_categorical,color_categorical,clarity_categorical]))



    ]

)

In [11]:
preprocessor=ColumnTransformer(


[

('num_pipeline',numeric_pipeline,x_num_data_col),
('cat_pipeline', categorical_pipeline,x_cat_data_col)

]
)

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.30,random_state=42)

In [13]:
preprocessor.fit_transform(x_train)

array([[-1.52430159, -0.82314374, -1.12998781, ...,  4.        ,
         1.        ,  5.        ],
       [-0.02588578,  0.94502267, -1.77782269, ...,  2.        ,
         4.        ,  4.        ],
       [ 1.57470775,  1.9584839 ,  0.16568195, ...,  3.        ,
         4.        ,  3.        ],
       ...,
       [ 0.6295683 ,  0.92345966,  0.90606467, ...,  3.        ,
         3.        ,  3.        ],
       [ 0.89668265, -1.03877378, -0.66724861, ...,  2.        ,
         3.        ,  6.        ],
       [ 0.45118206, -1.03877378, -0.01941373, ...,  2.        ,
         3.        ,  1.        ]])

In [14]:
preprocessor.transform(x_test)

array([[-1.46413603e+00, -6.29076691e-01,  2.58229791e-01, ...,
         4.00000000e+00,  0.00000000e+00,  2.00000000e+00],
       [ 1.23195721e+00,  2.60537405e+00, -2.14801405e+00, ...,
         2.00000000e+00,  3.00000000e+00,  1.00000000e+00],
       [-7.75441840e-05, -1.12502580e+00, -1.22253565e+00, ...,
         3.00000000e+00,  1.00000000e+00,  6.00000000e+00],
       ...,
       [-1.41033757e+00, -8.23143735e-01, -1.94137299e-02, ...,
         4.00000000e+00,  3.00000000e+00,  6.00000000e+00],
       [-4.25546794e-01,  9.01896659e-01, -6.67248611e-01, ...,
         3.00000000e+00,  5.00000000e+00,  2.00000000e+00],
       [-1.68954227e+00,  4.70636560e-01,  9.06064672e-01, ...,
         2.00000000e+00,  1.00000000e+00,  3.00000000e+00]])

In [15]:
preprocessor.get_feature_names_out()

array(['num_pipeline__id', 'num_pipeline__carat', 'num_pipeline__depth',
       'num_pipeline__table', 'num_pipeline__x', 'num_pipeline__y',
       'num_pipeline__z', 'cat_pipeline__cut', 'cat_pipeline__color',
       'cat_pipeline__clarity'], dtype=object)

In [16]:
x_train=pd.DataFrame(preprocessor.fit_transform(x_train),columns=preprocessor.get_feature_names_out())

In [17]:
x_test=pd.DataFrame(preprocessor.transform(x_test),columns=preprocessor.get_feature_names_out())

In [18]:
x_train.head()

,num_pipeline__id,num_pipeline__carat,num_pipeline__depth,num_pipeline__table,num_pipeline__x,num_pipeline__y,num_pipeline__z,cat_pipeline__cut,cat_pipeline__color,cat_pipeline__clarity
0,-1.524302,-0.823144,-1.129988,-0.641897,-0.780451,-0.835103,-0.876024,4.0,1.0,5.0
1,-0.025886,0.945023,-1.777823,0.921902,1.073226,1.166389,0.946633,2.0,4.0,4.0
2,1.574708,1.958484,0.165682,0.400636,1.703116,1.755063,1.742237,3.0,4.0,3.0
3,-1.633133,-0.995648,-0.574701,-0.641897,-1.122391,-1.161138,-1.165334,4.0,2.0,6.0
4,-0.916887,-0.995648,0.258230,0.400636,-1.176382,-1.152082,-1.136403,2.0,5.0,2.0

In [19]:
x_test.head()

,num_pipeline__id,num_pipeline__carat,num_pipeline__depth,num_pipeline__table,num_pipeline__x,num_pipeline__y,num_pipeline__z,cat_pipeline__cut,cat_pipeline__color,cat_pipeline__clarity
0,-1.464136,-0.629077,0.258230,-0.120630,-0.600482,-0.581521,-0.572248,4.0,0.0,2.0
1,1.231957,2.605374,-2.148014,-0.120630,2.126042,2.198832,1.959219,2.0,3.0,1.0
2,-0.000078,-1.125026,-1.222536,0.921902,-1.374347,-1.414721,-1.469110,3.0,1.0,6.0
3,0.873897,-1.017211,-0.574701,0.921902,-1.158385,-1.161138,-1.194265,3.0,5.0,6.0
4,0.392716,0.858771,0.628421,-0.641897,0.947248,0.985258,1.004495,4.0,4.0,2.0

In [43]:
# linear regression
# ridge regression
# lasso regression
# elastic regression
from sklearn.linear_model import LinearRegression,Lasso,ElasticNet,Ridge
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [72]:
models={
    'linearReression': LinearRegression(),
    'Lasso':Lasso(),
    'Ridge':Ridge(),
    'Elastic':ElasticNet()}

In [73]:
trained_model_list=[]
model_list=[]
r2_list=[]

In [74]:
import numpy as np
def evaluate_model(true,predict):
    mae=mean_absolute_error(true,predict)
    mse=mean_squared_error(true,predict)
    rmse=np.sqrt(mean_squared_error(true,predict))
    r2_square=r2_score(true,predict)
    return mae,rmse,r2_square

In [76]:
for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(x_train,y_train)
    #prediction
    y_predict=model.predict(x_test)

    #this is validation test score

    mae,rmse,r2_square=evaluate_model(y_test,y_predict)

    print(list(models.keys())[i])
    model_list.append( (list(models.keys())[i]))

    print ("model training performance")
    print("RMSE:",rmse)
    print("MAE:",mae)
    print("R2_SCORE:",r2_square)
    r2_list.append(r2_square)

    print("="*35)
    print("\n")

linearReression
model training performance
RMSE: 1014.6337606682042
MAE: 675.0760335549247
R2_SCORE: 0.9362901674122803
===================================


Lasso
model training performance
RMSE: 1014.6607134895941
MAE: 676.3783916049508
R2_SCORE: 0.9362867825800139
===================================


Ridge
model training performance
RMSE: 1014.63842140788
MAE: 675.1090061532639
R2_SCORE: 0.9362895821062558
===================================


Elastic
model training performance
RMSE: 1513.662539824099
MAE: 1051.18036294437
R2_SCORE: 0.8582098792147982
===================================

In [77]:
list(models)
models.values()
print(type(models))

<class 'dict'>